[tool.pytest.ini_options]
testpaths = ["tests"]
# rootdir = "."
pythonpath = ["."]
addopts = ["--verbose"]
# console_output_style = "count"

[tool.pylint]
disable = [
	"missing-function-docstring",
	"missing-module-docstring",
	"import-error",
	"missing-class-docstring",
	"too-few-public-methods",
	"too-many-instance-attributes",
	"line-too-long",
]
